### ISSUE TITLE
Problem Uploading Sketch

### ISSUE THREAD

**Issue by Wayphar** [MarkStrendin/TeensyWeddingGuestbook#1]
I'm having some problems uploading the Sketch.

Some help?

![image](https://github.com/MarkStrendin/TeensyWeddingGuestbook/assets/120519102/0a0ca8a8-c3aa-4422-92a7-383aaac30151)

Led Blink when i press button on Teensy.

**Comment by MarkStrendin** [comment]
Hello!

I'm not an expert on this kind of hardware, so I can really only offer a few suggestions.

First make sure you've installed the Teensy "Board" in the Arduino IDE by following the instructions here: https://www.pjrc.com/teensy/tutorial.html 

Then, you may need to run the Arduino IDE program as an administrator on Windows, or as root (or equivalent) on Linux or MacOS, so that it has the access to your hardware that it needs to talk to the board.

Lastly, there should be a little "virtual Teensy" window that pops up at some point, that has an option in it to automatically "push" the button on the teensy when it needs to upload code, so you don't have to constantly push it. This option might help if your button is hard or inconvenient to reach all the time (I accidentally attached my audio board overtop of the button the first time and couldn't reach it, for example).

If those suggestions don't work, then I apologize, I don't work with Arduinos often enough to know how to troubleshoot this further. You might try their official forums: https://forum.pjrc.com/

Best of luck!
